/*
 * File: leg_pos.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 15-Sep-2025 20:28:02
 */

/* Include Files */
#include "bipedal_wheel_controller/vmc/leg_pos.h"
#include "bipedal_wheel_controller/vmc/leg_params.h"
#include <stdio.h>
#include <math.h>

/* Function Definitions */
/*
 * LEG_POS
 *     POS = LEG_POS(PHI1,PHI2)
 *
 * Arguments    : double phi1
 *                double phi2
 *                double pos[2]
 * Return Type  : void
 */

void leg_pos(double phi1, double phi4, double pos[2])
{
  double a_tmp;
  double t4;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     15-Sep-2025 20:28:02 */
  t4 = phi1 + phi4;
  a_tmp = cos(phi1) * 0.218 + cos(t4) * 0.26;
  t4 = sin(phi1) * 0.218 + sin(t4) * 0.26;
  pos[0] = sqrt(a_tmp * a_tmp + t4 * t4);
  pos[1] = atan2(t4, a_tmp);
}

// void leg_pos(double phi1, double phi4, double pos[2])
//{
//   double a;
//   double t12;
//   double t13;
//   double t14;
//   double t15;
//   double t2;
//   double t3;
//   double t4;
//   double t5;
//   double t6;
//   double t8;
//   /*     This function was generated by the Symbolic Math Toolbox version 23.2.
//    */
//   /*     2025-10-13 22:10:52 */
//   t2 = cos(phi1);
//   t3 = cos(phi4);
//   t4 = sin(phi1);
//   t5 = sin(phi4);
//   t6 = t2 * 0.218;
//   t8 = t4 * 0.218;
//   t12 = t2 * 0.11336;
//   t13 = t3 * 0.11336;
//   t14 = t4 * 0.11336;
//   t15 = t5 * 0.11336;
//   a = t6 - t3 * 0.218;
//   t4 = t8 - t5 * 0.218;
//   t3 = t12 - t13;
//   t5 = t14 - t15;
//   t4 = a * a + t4 * t4;
//   t4 = atan(1.0 / ((t13 - t12) + t4) * ((t15 - t14) + sqrt((t3 * t3 + t5 * t5) - t4 * t4))) * 2.0;
//   t3 = cos(t4);
//   a = t6 + t3 * 0.26;
//   t4 = t8 + sin(t4) * 0.26;
//   pos[0] = sqrt(a * a + t4 * t4);
//   pos[1] = atan2(t2 * -0.218 - t3 * 0.26, t4);
// }

// void leg_pos(double phi1, double phi4, double pos[2])
//{
//   double YD, YB, XD, XB, lBD, A0, B0, C0, phi2, XC, YC;
//   double L0, Phi0;
//   YD = LEG_L4 * sin(phi4);
//   YB = LEG_L1 * sin(phi1);
//   XD = LEG_L5 + LEG_L4 * cos(phi4);
//   XB = LEG_L1 * cos(phi1);
//   lBD = sqrt((XD - XB) * (XD - XB) + (YD - YB) * (YD - YB));
//   A0 = 2 * LEG_L2 * (XD - XB);
//   B0 = 2 * LEG_L2 * (YD - YB);
//   C0 = LEG_L2 * LEG_L2 + lBD * lBD - LEG_L3 * LEG_L3;
//   phi2 = 2 * atan2((B0 + sqrt(A0 * A0 + B0 * B0 - C0 * C0)), (A0 + C0));
//   XC = LEG_L1 * cos(phi1) + LEG_L2 * cos(phi2);
//   YC = LEG_L1 * sin(phi1) + LEG_L2 * sin(phi2);
//   L0 = sqrt((XC - LEG_L5 / 2) * (XC - LEG_L5 / 2) + YC * YC);
//   Phi0 = -atan2((XC - LEG_L5 / 2), YC);
//   pos[0] = L0;
//   pos[1] = Phi0;
// }

/*
 * File trailer for leg_pos.c
 *
 * [EOF]
 */
