/*
 * File: leg_spd.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 15-Sep-2025 20:28:02
 */

/* Include Files */
#include "bipedal_wheel_controller/vmc/leg_spd.h"
#include "bipedal_wheel_controller/vmc/leg_params.h"
#include <math.h>

void CalcJacobian(double phi1, double phi4, double J_[2][2])
{
  double YD, YB, XD, XB, lBD, A0, B0, C0, XC, YC;
  double phi2, phi3;
  double L0, phi0;
  double j11, j12, j21, j22;

  YD = LEG_L4 * sin(phi4);
  YB = LEG_L1 * sin(phi1);
  XD = LEG_L5 + LEG_L4 * cos(phi4);
  XB = LEG_L1 * cos(phi1);
  lBD = sqrt((XD - XB) * (XD - XB) + (YD - YB) * (YD - YB));
  A0 = 2 * LEG_L2 * (XD - XB);
  B0 = 2 * LEG_L2 * (YD - YB);
  C0 = LEG_L2 * LEG_L2 + lBD * lBD - LEG_L3 * LEG_L3;
  phi2 = 2 * atan2((B0 + sqrt(A0 * A0 + B0 * B0 - C0 * C0)), A0 + C0);
  phi3 = atan2(YB - YD + LEG_L2 * sin(phi2), XB - XD + LEG_L2 * cos(phi2));
  XC = LEG_L1 * cos(phi1) + LEG_L2 * cos(phi2);
  YC = LEG_L1 * sin(phi1) + LEG_L2 * sin(phi2);
  L0 = sqrt((XC - LEG_L5 / 2) * (XC - LEG_L5 / 2) + YC * YC);
  phi0 = atan2(YC, XC - LEG_L5 / 2);

  j11 = (LEG_L1 * sin(phi0 - phi3) * sin(phi1 - phi2)) / sin(phi3 - phi2);
  j12 = (LEG_L4 * sin(phi0 - phi2) * sin(phi3 - phi4)) / sin(phi3 - phi2);
  j21 = (LEG_L1 * cos(phi0 - phi3) * sin(phi1 - phi2)) / (L0 * sin(phi3 - phi2));
  j22 = (LEG_L4 * cos(phi0 - phi2) * sin(phi3 - phi4)) / (L0 * sin(phi3 - phi2));

  J_[0][0] = j11;
  J_[0][1] = j12;
  J_[1][0] = j21;
  J_[1][1] = j22;
}

/* Function Definitions */
/*
 * LEG_SPD
 *     SPD = LEG_SPD(DPHI1,DPHI4,PHI1,PHI4)
 *
 * Arguments    : double dphi1
 *                double dphi4
 *                double phi1
 *                double phi4
 *                double spd[2]
 * Return Type  : void
 */
void leg_spd(double dphi1, double dphi4, double phi1, double phi4, double spd[2])
{
  double t29_tmp;
  double t30_tmp;
  double t32;
  double t34;
  double t35;
  double t37;
  double t37_tmp;
  double t5;
  double t9;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2025-09-15 20:28:02 */
  t5 = phi1 + phi4;
  t9 = cos(t5);
  t5 = sin(t5);
  t29_tmp = cos(phi1) * 0.14 + t9 / 4.0;
  t30_tmp = sin(phi1) * 0.14 + t5 / 4.0;
  t32 = t30_tmp * t30_tmp;
  t34 = t29_tmp * t29_tmp;
  t35 = 1.0 / t34;
  t37_tmp = t32 + t34;
  t37 = 1.0 / t37_tmp;
  spd[0] = dphi4 / sqrt(t37_tmp) * (t9 * t30_tmp / 2.0 - t5 * t29_tmp / 2.0) / 2.0;
  spd[1] =
      (dphi4 * t34 * t37 * (t9 / 4.0 / t29_tmp + t30_tmp * t35 * (t5 / 4.0)) + dphi1 * t34 * t37 * (t32 * t35 + 1.0));
}

// void leg_spd(double dphi1, double dphi4, double phi1, double phi4,
//              double spd[2])
//{
//   double t10_tmp;
//   double t12_tmp;
//   double t2;
//   double t21;
//   double t22;
//   double t23;
//   double t24;
//   double t29;
//   double t3;
//   double t30;
//   double t33;
//   double t34;
//   double t37;
//   double t38;
//   double t39;
//   double t4;
//   double t40;
//   double t5;
//   double t51;
//   double t57;
//   double t64;
//   double t66;
//   double t73;
//   double t81;
//   /*     This function was generated by the Symbolic Math Toolbox version 23.2.
//    */
//   /*     2025-10-13 22:10:53 */
//   t2 = cos(phi1);
//   t3 = cos(phi4);
//   t4 = sin(phi1);
//   t5 = sin(phi4);
//   t10_tmp = t2 * 0.218;
//   t12_tmp = t4 * 0.218;
//   t21 = t2 * 0.11336;
//   t22 = t3 * 0.11336;
//   t23 = t4 * 0.11336;
//   t24 = t5 * 0.11336;
//   t29 = t10_tmp - t3 * 0.218;
//   t30 = t12_tmp - t5 * 0.218;
//   t33 = t21 - t22;
//   t34 = t23 - t24;
//   t37 = t4 * t29 * 0.436;
//   t38 = t5 * t29 * 0.436;
//   t39 = t2 * t30 * 0.436;
//   t40 = t3 * t30 * 0.436;
//   t51 = t29 * t29 + t30 * t30;
//   t57 = 1.0 / ((t22 - t21) + t51);
//   t29 = t57 * t57;
//   t64 = sqrt((t33 * t33 + t34 * t34) - t51 * t51);
//   t30 = 1.0 / t64;
//   t66 = (t24 - t23) + t64;
//   t73 = atan(t57 * t66) * 2.0;
//   t64 = cos(t73);
//   t73 = sin(t73);
//   t81 = 1.0 / (t29 * (t66 * t66) + 1.0);
//   t37 = t29 * ((t23 + t39) - t37) * t66 +
//         t57 * (t21 - t30 *
//                          ((t2 * t34 * 0.22672 - t4 * t33 * 0.22672) +
//                           t51 * (t37 - t39) * 2.0) /
//                          2.0);
//   t29 = t29 * ((t24 + t40) - t38) * t66 +
//         t57 * (t22 - t30 *
//                          ((t3 * t34 * 0.22672 - t5 * t33 * 0.22672) +
//                           t51 * (t38 - t40) * 2.0) /
//                          2.0);
//   t4 = t10_tmp + t64 * 0.26;
//   t21 = t12_tmp + t73 * 0.26;
//   t2 = t64 * t81;
//   t23 = t2 * t29;
//   t64 = t73 * t81;
//   t66 = t64 * t29;
//   t51 = t21 * t21;
//   t57 = 1.0 / t21;
//   t30 = t51 + t4 * t4;
//   t29 = 1.0 / sqrt(t30);
//   t73 = 1.0 / t30;
//   t64 = t12_tmp - t64 * t37 * 0.52;
//   t30 = t10_tmp - t2 * t37 * 0.52;
//   spd[0] = dphi4 * t29 * (t21 * t23 * 1.04 - t4 * t66 * 1.04) / 2.0 +
//            dphi1 * t29 * (t21 * t30 * 2.0 - t4 * t64 * 2.0) / 2.0;
//   t29 = t4 * (1.0 / t51);
//   spd[1] = dphi1 * t51 * t73 * (t57 * t64 + t29 * t30) +
//            dphi4 * t51 * t73 * (t57 * (t66 * 0.52) - t29 * (0.0 - t23 * 0.52));
// }

// void leg_spd(double dphi1, double dphi4, double phi1, double phi4, double spd[2])
//{
//   double J[2][2];
//   CalcJacobian(phi1, phi4, J);
//   // clang-format off
//    double d_l0   = J[0][0] * dphi1 + J[0][1] * dphi4;
//    double d_phi0 = J[1][0] * dphi1 + J[1][1] * dphi4;
//   // clang-format on
//   spd[0] = d_l0;
//   spd[1] = d_phi0;
// }

/*
 * File trailer for leg_spd.c
 *
 * [EOF]
 */
