//
// Created by wk on 2026/2/25.
//

#include "bipedal_wheel_controller/vmc/VMC.h"
#include <math.h>

namespace rm_chassis_controllers
{
void VMC::leg_pos(double phi1, double phi4)
{
  double a_tmp;
  double t4;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     15-Sep-2025 20:28:02 */
  t4 = phi1 + phi4;
  a_tmp = cos(phi1) * l1_ + cos(t4) * l2_;
  t4 = sin(phi1) * l1_ + sin(t4) * l2_;
  pos_.L0 = sqrt(a_tmp * a_tmp + t4 * t4);
  pos_.theta = atan2(t4, a_tmp);

  // five link vmc
  //  double YD, YB, XD, XB, lBD, A0, B0, C0, phi2, XC, YC;
  //  double L0, Phi0;
  //  YD = l4_ * sin(phi4);
  //  YB = l1_ * sin(phi1);
  //  XD = l5_ + l4_ * cos(phi4);
  //  XB = l1_ * cos(phi1);
  //  lBD = sqrt((XD - XB) * (XD - XB) + (YD - YB) * (YD - YB));
  //  A0 = 2 * l2_ * (XD - XB);
  //  B0 = 2 * l2_ * (YD - YB);
  //  C0 = l2_ * l2_ + lBD * lBD - l3_ * l3_;
  //  phi2 = 2 * atan2((B0 + sqrt(A0 * A0 + B0 * B0 - C0 * C0)), (A0 + C0));
  //  XC = l1_ * cos(phi1) + l2_ * cos(phi2);
  //  YC = l1_ * sin(phi1) + l2_ * sin(phi2);
  //  L0 = sqrt((XC - l5_ / 2) * (XC - l5_ / 2) + YC * YC);
  //  Phi0 = -atan2((XC - l5_ / 2), YC);
  //  pos_.L0 = L0;
  //  pos_.theta = Phi0;
}

void VMC::leg_spd(double dphi1, double dphi4)
{
  static double last_L0_spd = J_[0][0] * dphi1 + J_[0][1] * dphi4;
  static double last_theta_spd = J_[1][0] * dphi1 + J_[1][1] * dphi4;

  // 速度映射
  spd_.dL0 = J_[0][0] * dphi1 + J_[0][1] * dphi4;     // dl0
  spd_.dTheta = J_[1][0] * dphi1 + J_[1][1] * dphi4;  // dphi0

  // leg_spd lp filter
  spd_.dL0 = 0.4 * spd_.dL0 + 0.6 * last_L0_spd;
  last_L0_spd = spd_.dL0;
  spd_.dTheta = 0.4 * spd_.dTheta + 0.6 * last_theta_spd;
  last_theta_spd = spd_.dTheta;
}

void VMC::leg_conv(double F, double Tp, double* T)
{
  // J^T * [F; Tp]
  T[0] = J_[0][0] * F + J_[1][0] * Tp;
  T[1] = J_[0][1] * F + J_[1][1] * Tp;
}

void VMC::calc_jacobian(double phi1, double phi4)
{
  phi1_ = phi1;
  phi4_ = phi4;
  // gazebo
  double phi2 = phi1 + phi4;

  double c1 = cos(phi1);
  double s1 = sin(phi1);
  double c2 = cos(phi2);
  double s2 = sin(phi2);

  // 末端笛卡尔坐标
  double Cx = l1_ * c1 + l2_ * c2;
  double Cy = l1_ * s1 + l2_ * s2;

  double L0 = sqrt(Cx * Cx + Cy * Cy);

  // 防止奇异
  if (L0 < 1e-8)
  {
    J_[0][0] = J_[0][1] = 0.0;
    J_[1][0] = J_[1][1] = 0.0;
    return;
  }

  // 偏导
  double dx_dphi1 = -l1_ * s1 - l2_ * s2;
  double dy_dphi1 = l1_ * c1 + l2_ * c2;

  double dx_dphi4 = -l2_ * s2;
  double dy_dphi4 = l2_ * c2;

  double inv_L0 = 1.0 / L0;
  double inv_L0_sq = 1.0 / (L0 * L0);

  // 第一行：dl0/dphi
  J_[0][0] = (Cx * dx_dphi1 + Cy * dy_dphi1) * inv_L0;
  J_[0][1] = (Cx * dx_dphi4 + Cy * dy_dphi4) * inv_L0;

  // 第二行：dphi0/dphi
  J_[1][0] = (Cx * dy_dphi1 - Cy * dx_dphi1) * inv_L0_sq;
  J_[1][1] = (Cx * dy_dphi4 - Cy * dx_dphi4) * inv_L0_sq;

  // five link vmc
  //  double YD, YB, XD, XB, lBD, A0, B0, C0, XC, YC;
  //  double phi2, phi3;
  //  double L0, phi0;
  //  double j11, j12, j21, j22;
  //
  //  YD = l4_ * sin(phi4);
  //  YB = l1_ * sin(phi1);
  //  XD = l5_ + l4_ * cos(phi4);
  //  XB = l1_ * cos(phi1);
  //  lBD = sqrt((XD - XB) * (XD - XB) + (YD - YB) * (YD - YB));
  //  A0 = 2 * l2_ * (XD - XB);
  //  B0 = 2 * l2_ * (YD - YB);
  //  C0 = l2_ * l2_ + lBD * lBD - l3_ * l3_;
  //  phi2 = 2 * atan2((B0 + sqrt(A0 * A0 + B0 * B0 - C0 * C0)), A0 + C0);
  //  phi3 = atan2(YB - YD + l2_ * sin(phi2), XB - XD + l2_ * cos(phi2));
  //  XC = l1_ * cos(phi1) + l2_ * cos(phi2);
  //  YC = l1_ * sin(phi1) + l2_ * sin(phi2);
  //  L0 = sqrt((XC - l5_ / 2) * (XC - l5_ / 2) + YC * YC);
  //  phi0 = atan2(YC, XC - l5_ / 2);
  //
  //  j11 = (l1_ * sin(phi0 - phi3) * sin(phi1 - phi2)) / sin(phi3 - phi2);
  //  j12 = (l4_ * sin(phi0 - phi2) * sin(phi3 - phi4)) / sin(phi3 - phi2);
  //  j21 = (l1_ * cos(phi0 - phi3) * sin(phi1 - phi2)) / (L0 * sin(phi3 - phi2));
  //  j22 = (l4_ * cos(phi0 - phi2) * sin(phi3 - phi4)) / (L0 * sin(phi3 - phi2));
  //
  //  J_[0][0] = j11;
  //  J_[0][1] = j12;
  //  J_[1][0] = j21;
  //  J_[1][1] = j22;
}

inline void VMC::calc_jacobian(double phi1, double phi4, double J[2][2])
{
  phi1_ = phi1;
  phi4_ = phi4;
  // gazebo
  //  double phi2 = phi1 + phi4;
  //
  //  double c1 = cos(phi1);
  //  double s1 = sin(phi1);
  //  double c2 = cos(phi2);
  //  double s2 = sin(phi2);
  //
  //  // 末端笛卡尔坐标
  //  double Cx = l1_ * c1 + l2_ * c2;
  //  double Cy = l1_ * s1 + l2_ * s2;
  //
  //  double L0 = sqrt(Cx * Cx + Cy * Cy);
  //
  //  // 防止奇异
  //  if (L0 < 1e-8)
  //  {
  //    J[0][0] = J[0][1] = 0.0;
  //    J[1][0] = J[1][1] = 0.0;
  //    return;
  //  }
  //
  //  // 偏导
  //  double dx_dphi1 = -l1_ * s1 - l2_ * s2;
  //  double dy_dphi1 = l1_ * c1 + l2_ * c2;
  //
  //  double dx_dphi4 = -l2_ * s2;
  //  double dy_dphi4 = l2_ * c2;
  //
  //  double inv_L0 = 1.0 / L0;
  //  double inv_L0_sq = 1.0 / (L0 * L0);
  //
  //  // 第一行：dl0/dphi
  //  J[0][0] = (Cx * dx_dphi1 + Cy * dy_dphi1) * inv_L0;
  //  J[0][1] = (Cx * dx_dphi4 + Cy * dy_dphi4) * inv_L0;
  //
  //  // 第二行：dphi0/dphi
  //  J[1][0] = (Cx * dy_dphi1 - Cy * dx_dphi1) * inv_L0_sq;
  //  J[1][1] = (Cx * dy_dphi4 - Cy * dx_dphi4) * inv_L0_sq;

  // five link vmc
  double YD, YB, XD, XB, lBD, A0, B0, C0, XC, YC;
  double phi2, phi3;
  double L0, phi0;
  double j11, j12, j21, j22;

  YD = l4_ * sin(phi4);
  YB = l1_ * sin(phi1);
  XD = l5_ + l4_ * cos(phi4);
  XB = l1_ * cos(phi1);
  lBD = sqrt((XD - XB) * (XD - XB) + (YD - YB) * (YD - YB));
  A0 = 2 * l2_ * (XD - XB);
  B0 = 2 * l2_ * (YD - YB);
  C0 = l2_ * l2_ + lBD * lBD - l3_ * l3_;
  phi2 = 2 * atan2((B0 + sqrt(A0 * A0 + B0 * B0 - C0 * C0)), A0 + C0);
  phi3 = atan2(YB - YD + l2_ * sin(phi2), XB - XD + l2_ * cos(phi2));
  XC = l1_ * cos(phi1) + l2_ * cos(phi2);
  YC = l1_ * sin(phi1) + l2_ * sin(phi2);
  L0 = sqrt((XC - l5_ / 2) * (XC - l5_ / 2) + YC * YC);
  phi0 = atan2(YC, XC - l5_ / 2);

  j11 = (l1_ * sin(phi0 - phi3) * sin(phi1 - phi2)) / sin(phi3 - phi2);
  j12 = (l4_ * sin(phi0 - phi2) * sin(phi3 - phi4)) / sin(phi3 - phi2);
  j21 = (l1_ * cos(phi0 - phi3) * sin(phi1 - phi2)) / (L0 * sin(phi3 - phi2));
  j22 = (l4_ * cos(phi0 - phi2) * sin(phi3 - phi4)) / (L0 * sin(phi3 - phi2));

  J[0][0] = j11;
  J[0][1] = j12;
  J[1][0] = j21;
  J[1][1] = j22;
}

void VMC::leg_conv_t(double T1, double T2)
{
  // (J^T)^-1 * [T1; T2]
  double det = J_[0][0] * J_[1][1] - J_[0][1] * J_[1][0];
  if (fabs(det) < 1e-8)
  {
    force_real_.F = force_real_.Tp = 0.0;  // 奇异情况
    return;
  }
  double inv_Jt[2][2];
  inv_Jt[0][0] = J_[1][1] / det;
  inv_Jt[0][1] = -J_[0][1] / det;
  inv_Jt[1][0] = -J_[1][0] / det;
  inv_Jt[1][1] = J_[0][0] / det;

  force_real_.F = inv_Jt[0][0] * T1 + inv_Jt[0][1] * T2;   // F
  force_real_.Tp = inv_Jt[1][0] * T1 + inv_Jt[1][1] * T2;  // Tp

  // five link vmc
  //  double YD, YB, XD, XB, lBD, A0, B0, C0, XC, YC;
  //  double phi2, phi3;
  //  double L0, phi0;
  //
  //  YD = l4_ * sin(phi4_);
  //  YB = l1_ * sin(phi1_);
  //  XD = l5_ + l4_ * cos(phi4_);
  //  XB = l1_ * cos(phi1_);
  //  lBD = sqrt((XD - XB) * (XD - XB) + (YD - YB) * (YD - YB));
  //  A0 = 2 * l2_ * (XD - XB);
  //  B0 = 2 * l2_ * (YD - YB);
  //  C0 = l2_ * l2_ + lBD * lBD - l3_ * l3_;
  //  phi2 = 2 * atan2((B0 + sqrt(A0 * A0 + B0 * B0 - C0 * C0)), A0 + C0);
  //  phi3 = atan2(YB - YD + l2_ * sin(phi2), XB - XD + l2_ * cos(phi2));
  //  XC = l1_ * cos(phi1_) + l2_ * cos(phi2);
  //  YC = l1_ * sin(phi1_) + l2_ * sin(phi2);
  //  L0 = sqrt((XC - l5_ / 2) * (XC - l5_ / 2) + YC * YC);
  //  phi0 = atan2(YC, XC - l5_ / 2);
  //
  //  double f_temp_11 = cos(phi0 - phi3);
  //  double f_temp_12 = cos(phi0 - phi2);
  //  double f_temp_21 = l4_ * sin(phi3 - phi4_);
  //  double f_temp_22 = l1_ * sin(phi1_ - phi2);
  //
  //  double t_temp_11 = cos(phi0 - phi2);
  //  double t_temp_12 = sin(phi0 - phi3);
  //  double t_temp_21 = l1_ * sin(phi1_ - phi2);
  //  double t_temp_22 = l4_ * sin(phi3 - phi4_);
  //
  //  double inv_Jt[2][2];
  //  inv_Jt[0][0] = -f_temp_12 / f_temp_22;
  //  inv_Jt[0][1] = f_temp_11 / f_temp_21;
  //  inv_Jt[1][0] = L0 * t_temp_11 / t_temp_21;
  //  inv_Jt[1][1] = -L0 * t_temp_12 / t_temp_22;
  //
  //  force_real_.F = inv_Jt[0][0] * T1 + inv_Jt[0][1] * T2;   // F
  //  force_real_.Tp = inv_Jt[1][0] * T1 + inv_Jt[1][1] * T2;  // Tp
}
}  // namespace rm_chassis_controllers
