/*
 * File: gen_B.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 08-Aug-2025 17:37:08
 */

/* Include Files */
#include "bipedal_wheel_controller/dynamics/gen_B.h"

/* Function Definitions */
/*
 * gen_B
 *     B = gen_B(Im,Ip,Iw,L,Lm,M,R,l,MP,MW)
 *
 * Arguments    : double Im
 *                double Ip
 *                double Iw
 *                double L
 *                double Lm
 *                double M
 *                double R
 *                double l
 *                double mp
 *                double mw
 *                double B[12]
 * Return Type  : void
 */
void gen_B(double Im, double Ip, double Iw, double L, double Lm, double M, double R, double l, double mp, double mw,
           double B[12])
{
  double t10;
  double t10_tmp;
  double t11;
  double t13;
  double t14;
  double t14_tmp;
  double t15;
  double t15_tmp;
  double t16;
  double t16_tmp;
  double t17;
  double t2;
  double t22;
  double t22_tmp;
  double t23;
  double t23_tmp;
  double t28;
  double t28_tmp;
  double t29;
  double t3;
  double t30;
  double t31;
  double t32;
  double t32_tmp;
  double t33;
  double t33_tmp;
  double t4;
  double t44;
  double t44_tmp;
  double t5;
  double t6;
  double t8;
  double t8_tmp;
  double t9;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2025-12-05 01:47:45 */
  t2 = L * L;
  t3 = Lm * Lm;
  t4 = R * R;
  t5 = l * l;
  t6 = Im * Iw;
  t8_tmp = Im * L;
  t8 = t8_tmp * M * R;
  t9 = Im * Lm * M * R;
  t10_tmp = Iw * L;
  t10 = t10_tmp * M * l;
  t11 = Iw * Lm * M * l;
  t13 = t8_tmp * R * mp;
  t44 = L * Lm;
  t22_tmp = t44 * M;
  t22 = t22_tmp * R * l * mp;
  t14_tmp = Im * M;
  t14 = t14_tmp * t4;
  t15_tmp = Iw * M;
  t15 = t15_tmp * t5;
  t16_tmp = Im * mp;
  t16 = t16_tmp * t4;
  t17 = Im * mw * t4;
  t23_tmp = Ip * M;
  t23 = -(t23_tmp * R * l);
  t28_tmp = L * M;
  t28 = t28_tmp * R * mp * t5;
  t29 = t28_tmp * l * mw * t4;
  t28_tmp = Lm * M * l;
  t30 = t28_tmp * mp * t4;
  t31 = t28_tmp * mw * t4;
  t32_tmp = M * mp;
  t32 = t32_tmp * t4 * t5;
  t33_tmp = M * mw;
  t33 = t33_tmp * t4 * t5;
  t28_tmp = mp * t2;
  t44_tmp = mw * t2;
  t44 =
      1.0 /
      (((((((((((((((((Ip * t6 + Ip * t15) + t28_tmp * t6) + Ip * t16) + Ip * t17) + t22_tmp * t6 * 2.0) + M * t2 * t6) +
                 M * t3 * t6) +
                Ip * t14) +
               t44 * mw * t14 * 2.0) +
              t44_tmp * t14) +
             mp * t3 * t14) +
            mw * t3 * t14) +
           t28_tmp * t15) +
          Ip * t32) +
         Ip * t33) +
        t44_tmp * t16) +
       t44_tmp * t32);
  B[0] = 0.0;
  B[1] = -t44 * ((((((((((t6 + t8) + t9) + t13) + t14) + t15) + t16) + t17) + t28) + t32) + t33);
  B[2] = 0.0;
  t44_tmp = (t8 + t9) + t13;
  B[3] = R * t44 *
         ((((((((t44_tmp + t28) + Im * Ip) + t14_tmp * t2) + t14_tmp * t3) + t23_tmp * t5) + t16_tmp * t2) +
           t32_tmp * t2 * t5) +
          t8_tmp * Lm * M * 2.0);
  B[4] = 0.0;
  t28_tmp = t10 + t11;
  B[5] = -t44 * (((((t28_tmp + t22) + t23) + t29) + t30) + t31);
  B[6] = 0.0;
  B[7] = t44 * (((((((((((t6 + t10) + t11) + t14) + t15) + t16) + t17) + t29) + t30) + t31) + t32) + t33);
  B[8] = 0.0;
  B[9] = -R * t44 * (((t44_tmp + t22) + t23) + t28);
  B[10] = 0.0;
  B[11] =
      t44 * ((((((((((((((((t28_tmp + t29) + t30) + t31) + Ip * Iw) + t23_tmp * t4) + t15_tmp * t2) + t15_tmp * t3) +
                     Ip * mp * t4) +
                    Iw * mp * t2) +
                   Ip * mw * t4) +
                  t32_tmp * t3 * t4) +
                 t33_tmp * t2 * t4) +
                t33_tmp * t3 * t4) +
               mp * mw * t2 * t4) +
              t10_tmp * Lm * M * 2.0) +
             t22_tmp * mw * t4 * 2.0);
}

/* Function Definitions */
/*
 * gen_B_leg_offset
 *     B = gen_B_leg_offset(Im,Ip,Iw,L,Lm,M,R,G,l,MP,MW,THETA_L0)
 *
 * Arguments    : double Im
 *                double Ip
 *                double Iw
 *                double L
 *                double Lm
 *                double M
 *                double R
 *                double g
 *                double l
 *                double mp
 *                double mw
 *                double theta_l0
 *                double B[12]
 * Return Type  : void
 */
void gen_B_leg_offset(double Im, double Ip, double Iw, double L, double Lm, double M, double R, double g, double l,
                      double mp, double mw, double theta_l0, double B[12])
{
  double b_t39_tmp;
  double t12;
  double t13;
  double t13_tmp;
  double t14;
  double t14_tmp;
  double t15;
  double t15_tmp;
  double t16;
  double t2;
  double t22;
  double t22_tmp;
  double t25;
  double t25_tmp;
  double t26;
  double t27;
  double t28;
  double t29;
  double t29_tmp;
  double t3;
  double t30;
  double t30_tmp;
  double t39;
  double t39_tmp;
  double t4;
  double t5;
  double t7;
  double t7_tmp;
  double t9;
  double t9_tmp;
  (void)g;
  (void)theta_l0;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2026-03-02 20:29:44 */
  t2 = L * L;
  t3 = R * R;
  t4 = l * l;
  t5 = Im * Iw;
  t7_tmp = Im * L;
  t7 = t7_tmp * M * R;
  t9_tmp = Iw * L;
  t9 = t9_tmp * M * l;
  t12 = t7_tmp * R * mp;
  t13_tmp = Im * M;
  t13 = t13_tmp * t3;
  t14_tmp = Iw * M;
  t14 = t14_tmp * t4;
  t15_tmp = Im * mp;
  t15 = t15_tmp * t3;
  t16 = Im * mw * t3;
  t22_tmp = Ip * M;
  t22 = -(t22_tmp * R * l);
  t25_tmp = L * M;
  t25 = t25_tmp * R * mp * t4;
  t26 = t25_tmp * l * mw * t3;
  t25_tmp = Lm * M * l;
  t27 = t25_tmp * mp * t3;
  t28 = t25_tmp * mw * t3;
  t29_tmp = M * mp;
  t29 = t29_tmp * t3 * t4;
  t30_tmp = M * mw;
  t30 = t30_tmp * t3 * t4;
  t25_tmp = L * Lm;
  t39_tmp = mp * t2;
  t39 = mw * t2;
  b_t39_tmp = t25_tmp * M;
  t39 =
      1.0 / ((((((((((((((Ip * t5 + b_t39_tmp * t5) + Ip * t14) + t39_tmp * t5) + Ip * t15) + Ip * t16) + M * t2 * t5) +
                    Ip * t13) +
                   t25_tmp * mw * t13) +
                  t39 * t13) +
                 t39_tmp * t14) +
                Ip * t29) +
               Ip * t30) +
              t39 * t15) +
             t39 * t29);
  B[0] = 0.0;
  B[1] = -t39 * (((((((((t5 + t7) + t12) + t13) + t14) + t15) + t16) + t25) + t29) + t30);
  B[2] = 0.0;
  t39_tmp = (t7 + Im * Lm * M * R) + t12;
  B[3] = R * t39 *
         (((((((t39_tmp + t25) + Im * Ip) + t13_tmp * t2) + t22_tmp * t4) + t15_tmp * t2) + t29_tmp * t2 * t4) +
          t7_tmp * Lm * M);
  B[4] = 0.0;
  t25_tmp = t9 + Iw * Lm * M * l;
  B[5] = -t39 * (((((t25_tmp + t22) + t26) + t27) + t28) + b_t39_tmp * R * l * mp);
  B[6] = 0.0;
  B[7] = t39 * ((((((((t5 + t9) + t13) + t14) + t15) + t16) + t26) + t29) + t30);
  B[8] = 0.0;
  B[9] = -R * t39 * ((t39_tmp + t22) + t25);
  B[10] = 0.0;
  B[11] = t39 * (((((((((((((t25_tmp + t26) + t27) + t28) + Ip * Iw) + t22_tmp * t3) + t14_tmp * t2) + Ip * mp * t3) +
                      Iw * mp * t2) +
                     Ip * mw * t3) +
                    t30_tmp * t2 * t3) +
                   mp * mw * t2 * t3) +
                  t9_tmp * Lm * M) +
                 b_t39_tmp * mw * t3);
}

/*
 * File trailer for gen_B.c
 *
 * [EOF]
 */
