/*
 * File: gen_A.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 08-Aug-2025 17:34:32
 */

/* Include Files */
#include "bipedal_wheel_controller/dynamics/gen_A.h"
#include <math.h>
#include <string.h>

/* Function Definitions */
/*
 * gen_A
 *     A = gen_A(Im,Ip,Iw,L,Lm,M,R,G,l,MP,MW)
 *
 * Arguments    : double Im
 *                double Ip
 *                double Iw
 *                double L
 *                double Lm
 *                double M
 *                double R
 *                double g
 *                double l
 *                double mp
 *                double mw
 *                double A[36]
 * Return Type  : void
 */
void gen_A(double Im, double Ip, double Iw, double L, double Lm, double M, double R, double g, double l, double mp,
           double mw, double A[36])
{
  double b_t22_tmp;
  double b_t35_tmp;
  double b_t42_tmp;
  double c_t42_tmp;
  double d;
  double d1;
  double d_t42_tmp;
  double e_t42_tmp;
  double f_t42_tmp;
  double g_t42_tmp;
  double h_t42_tmp;
  double i_t42_tmp;
  double j_t42_tmp;
  double k_t42_tmp;
  double t17_tmp;
  double t2;
  double t22_tmp;
  double t24_tmp;
  double t3;
  double t31;
  double t31_tmp;
  double t33_tmp;
  double t34_tmp;
  double t35_tmp;
  double t36_tmp;
  double t4;
  double t42;
  double t42_tmp;
  double t5;
  double t6;
  double t7;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2025-12-05 01:47:45 */
  t2 = L * L;
  t3 = Lm * Lm;
  t4 = M * M;
  t5 = R * R;
  t6 = l * l;
  t7 = mp * mp;
  t17_tmp = Iw * M;
  t22_tmp = Iw * L;
  b_t22_tmp = t22_tmp * Lm;
  t24_tmp = Iw * g * l;
  t31_tmp = L * Lm;
  t31 = t31_tmp * R * g * mp * t4 * t6;
  t33_tmp = t31_tmp * g * l;
  t34_tmp = L * g;
  t35_tmp = g * l;
  b_t35_tmp = t35_tmp * mw;
  t36_tmp = Lm * g;
  t42_tmp = Im * Ip;
  b_t42_tmp = Im * Iw;
  c_t42_tmp = b_t42_tmp * M;
  d_t42_tmp = Im * M;
  e_t42_tmp = d_t42_tmp * mw;
  f_t42_tmp = Ip * M;
  g_t42_tmp = b_t42_tmp * L;
  h_t42_tmp = Im * L;
  i_t42_tmp = h_t42_tmp * Lm;
  j_t42_tmp = i_t42_tmp * M;
  k_t42_tmp = Ip * Iw * M;
  t42 =
      1.0 /
      (((((((((((((((((t42_tmp * Iw + k_t42_tmp * t6) + b_t42_tmp * mp * t2) + t42_tmp * mp * t5) + t42_tmp * mw * t5) +
                   g_t42_tmp * Lm * M * 2.0) +
                  c_t42_tmp * t2) +
                 c_t42_tmp * t3) +
                t42_tmp * M * t5) +
               j_t42_tmp * mw * t5 * 2.0) +
              e_t42_tmp * t2 * t5) +
             d_t42_tmp * mp * t3 * t5) +
            e_t42_tmp * t3 * t5) +
           t17_tmp * mp * t2 * t6) +
          f_t42_tmp * mp * t5 * t6) +
         f_t42_tmp * mw * t5 * t6) +
        Im * mp * mw * t2 * t5) +
       M * mp * mw * t2 * t5 * t6);
  A[0] = 0.0;
  d = h_t42_tmp * g;
  c_t42_tmp = h_t42_tmp * M * g;
  e_t42_tmp = Im * Lm;
  h_t42_tmp = e_t42_tmp * M * g;
  d1 = L * M * g;
  t42_tmp =
      (((t22_tmp * g * t4 * t6 + Iw * Lm * g * t4 * t6) + t34_tmp * mw * t4 * t5 * t6) + t36_tmp * mp * t4 * t5 * t6) +
      t36_tmp * mw * t4 * t5 * t6;
  A[1] = t42 * (((((((((((((((t42_tmp + g_t42_tmp * g * mp) + d * t4 * t5) + d * t5 * t7) + e_t42_tmp * g * t4 * t5) +
                          g_t42_tmp * M * g) +
                         b_t42_tmp * Lm * M * g) +
                        c_t42_tmp * mp * t5 * 2.0) +
                       c_t42_tmp * mw * t5) +
                      t22_tmp * M * g * mp * t6) +
                     h_t42_tmp * mp * t5) +
                    h_t42_tmp * mw * t5) +
                   d * mp * mw * t5) +
                  d1 * t5 * t6 * t7) +
                 t34_tmp * mp * t4 * t5 * t6) +
                d1 * mp * mw * t5 * t6);
  A[2] = 0.0;
  d = Im * R * g;
  c_t42_tmp = d * t2;
  e_t42_tmp = -R * t42;
  A[3] = e_t42_tmp * ((((((((t31 + c_t42_tmp * t4) + d * t3 * t4) + c_t42_tmp * t7) + i_t42_tmp * R * g * t4 * 2.0) +
                         d_t42_tmp * R * g * mp * t2 * 2.0) +
                        M * R * g * t2 * t6 * t7) +
                       R * g * mp * t2 * t4 * t6) +
                      j_t42_tmp * R * g * mp * 2.0);
  A[4] = 0.0;
  d = t31_tmp * M * g * l;
  c_t42_tmp =
      (((((((t17_tmp * g * l * mp * t2 + b_t22_tmp * g * l * t4 * 2.0) + t24_tmp * t2 * t4) + t24_tmp * t3 * t4) +
          M * g * l * mp * mw * t2 * t5) +
         t33_tmp * mw * t4 * t5 * 2.0) +
        b_t35_tmp * t2 * t4 * t5) +
       t35_tmp * mp * t3 * t4 * t5) +
      b_t35_tmp * t3 * t4 * t5;
  A[5] = t42 * ((((c_t42_tmp + t33_tmp * mp * t4 * t5) + b_t22_tmp * M * g * l * mp) + d * t5 * t7) + d * mp * mw * t5);
  A[6] = 1.0;
  memset(&A[7], 0, 13U * sizeof(double));
  A[20] = 1.0;
  A[21] = 0.0;
  A[22] = 0.0;
  A[23] = 0.0;
  A[24] = 0.0;
  A[25] = t42 * t42_tmp;
  A[26] = 0.0;
  A[27] = e_t42_tmp * (t31 - Ip * R * g * t4 * t6);
  A[28] = 0.0;
  d = f_t42_tmp * g * l;
  A[29] = t42 * ((((c_t42_tmp + k_t42_tmp * g * l) + Ip * g * l * t4 * t5) + d * mp * t5) + d * mw * t5);
  A[30] = 0.0;
  A[31] = 0.0;
  A[32] = 0.0;
  A[33] = 0.0;
  A[34] = 1.0;
  A[35] = 0.0;
}

/* Function Definitions */
/*
 * gen_A_leg_offset
 *     A = gen_A_leg_offset(Im,Ip,Iw,L,Lm,M,R,G,l,MP,MW,THETA_L0)
 *
 * Arguments    : double Im
 *                double Ip
 *                double Iw
 *                double L
 *                double Lm
 *                double M
 *                double R
 *                double g
 *                double l
 *                double mp
 *                double mw
 *                double theta_l0
 *                double A[36]
 * Return Type  : void
 */
void gen_A_leg_offset(double Im, double Ip, double Iw, double L, double Lm, double M, double R, double g, double l,
                      double mp, double mw, double theta_l0, double A[36])
{
  double b_t18_tmp;
  double b_t19_tmp;
  double b_t27_tmp;
  double b_t28_tmp;
  double b_t33_tmp;
  double c_t33_tmp;
  double d;
  double d1;
  double d2;
  double d3;
  double d_t33_tmp;
  double e_t33_tmp;
  double f_t33_tmp;
  double g_t33_tmp;
  double h_t33_tmp;
  double i_t33_tmp;
  double t18_tmp;
  double t19_tmp;
  double t2;
  double t27_tmp;
  double t28_tmp;
  double t29_tmp;
  double t3;
  double t33;
  double t33_tmp;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2026-03-02 20:29:44 */
  t2 = cos(theta_l0);
  t3 = L * L;
  t4 = Lm * Lm;
  t5 = M * M;
  t6 = R * R;
  t7 = l * l;
  t8 = mp * mp;
  t18_tmp = Iw * L;
  b_t18_tmp = t18_tmp * Lm;
  t19_tmp = Iw * M;
  b_t19_tmp = t19_tmp * g * l * mp;
  t27_tmp = L * Lm;
  b_t27_tmp = t27_tmp * g * l;
  t28_tmp = M * g * l;
  b_t28_tmp = t28_tmp * mp * mw;
  t29_tmp = L * g;
  t33_tmp = Im * Iw;
  b_t33_tmp = Im * Ip;
  c_t33_tmp = Ip * M;
  d_t33_tmp = t33_tmp * L;
  e_t33_tmp = Im * L;
  f_t33_tmp = e_t33_tmp * Lm;
  g_t33_tmp = Im * M;
  h_t33_tmp = f_t33_tmp * M;
  i_t33_tmp = Ip * Iw * M;
  t33 =
      1.0 /
      ((((((((((((((b_t33_tmp * Iw + d_t33_tmp * Lm * M) + i_t33_tmp * t7) + t33_tmp * mp * t3) + b_t33_tmp * mp * t6) +
                b_t33_tmp * mw * t6) +
               t33_tmp * M * t3) +
              b_t33_tmp * M * t6) +
             h_t33_tmp * mw * t6) +
            g_t33_tmp * mw * t3 * t6) +
           t19_tmp * mp * t3 * t7) +
          c_t33_tmp * mp * t6 * t7) +
         c_t33_tmp * mw * t6 * t7) +
        Im * mp * mw * t3 * t6) +
       M * mp * mw * t3 * t6 * t7);
  A[0] = 0.0;
  d = e_t33_tmp * g;
  t19_tmp = e_t33_tmp * M * g;
  b_t33_tmp = Im * Lm;
  e_t33_tmp = b_t33_tmp * g;
  d1 = L * M * g;
  d2 = Lm * M * g;
  d3 = t18_tmp * g * t5 * t7 + t29_tmp * mw * t5 * t6 * t7;
  A[1] = t33 * ((((((((((((((((((d3 + d_t33_tmp * g * mp) + d * t5 * t6) + d * t6 * t8) + d_t33_tmp * M * g) -
                             t33_tmp * Lm * g * mp * t2) +
                            t19_tmp * mp * t6 * 2.0) +
                           t19_tmp * mw * t6) +
                          t18_tmp * M * g * mp * t7) +
                         d * mp * mw * t6) -
                        e_t33_tmp * t2 * t6 * t8) +
                       d1 * t6 * t7 * t8) +
                      t29_tmp * mp * t5 * t6 * t7) -
                     e_t33_tmp * mp * mw * t2 * t6) +
                    d1 * mp * mw * t6 * t7) -
                   d2 * t2 * t6 * t7 * t8) -
                  b_t33_tmp * M * g * mp * t2 * t6) -
                 Iw * Lm * M * g * mp * t2 * t7) -
                d2 * mp * mw * t2 * t6 * t7);
  A[2] = 0.0;
  d = Im * R * g * t3;
  t19_tmp = g_t33_tmp * R * g * mp;
  b_t33_tmp = f_t33_tmp * R * g;
  e_t33_tmp = h_t33_tmp * R * g * mp;
  d1 = t27_tmp * M;
  A[3] = -R * t33 *
         ((((((((((d * t5 + d * t8) + b_t33_tmp * t5) + t19_tmp * t3 * 2.0) + M * R * g * t3 * t7 * t8) +
               R * g * mp * t3 * t5 * t7) -
              t19_tmp * t2 * t4) +
             e_t33_tmp) -
            b_t33_tmp * t2 * t8) -
           e_t33_tmp * t2) -
          d1 * R * g * t2 * t7 * t8);
  A[4] = 0.0;
  d = b_t18_tmp * M * g * l * mp;
  t19_tmp = d1 * g * l;
  b_t33_tmp = t19_tmp * mp * mw;
  e_t33_tmp = ((((b_t18_tmp * g * l * t5 + b_t19_tmp * t3) + Iw * g * l * t3 * t5) + b_t27_tmp * mw * t5 * t6) +
               b_t28_tmp * t3 * t6) +
              g * l * mw * t3 * t5 * t6;
  A[5] =
      t33 * (((((((((e_t33_tmp - b_t19_tmp * t2 * t4) + b_t27_tmp * mp * t5 * t6) - t28_tmp * t2 * t4 * t6 * t8) + d) +
                 t19_tmp * t6 * t8) -
                d * t2) +
               b_t33_tmp * t6) -
              b_t28_tmp * t2 * t4 * t6) -
             b_t33_tmp * t2 * t6);
  A[6] = 1.0;
  memset(&A[7], 0, 13U * sizeof(double));
  A[20] = 1.0;
  A[21] = 0.0;
  A[22] = 0.0;
  A[23] = 0.0;
  A[24] = 0.0;
  A[25] = t33 * d3;
  A[26] = 0.0;
  d = Ip * g;
  A[27] = d * t5 * t6 * t7 * t33;
  A[28] = 0.0;
  t19_tmp = c_t33_tmp * g * l;
  A[29] = t33 * ((((e_t33_tmp + i_t33_tmp * g * l) + d * l * t5 * t6) + t19_tmp * mp * t6) + t19_tmp * mw * t6);
  A[30] = 0.0;
  A[31] = 0.0;
  A[32] = 0.0;
  A[33] = 0.0;
  A[34] = 1.0;
  A[35] = 0.0;
}

/*
 * File trailer for gen_A.c
 *
 * [EOF]
 */
