controllers:
  shooter_controller:
    type: rm_shooter_controllers/Controller
    publish_rate: 50
    friction_left:
      joint: "left_friction_wheel_joint"
      pid: { p: 0.002, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    friction_right:
      joint: "right_friction_wheel_joint"
      pid: { p: 0.002, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    trigger:
      joint: "trigger_joint"
      pid: { p: 40.0, i: 0.0, d: 2.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
    push_per_rotation: 6
    push_qd_threshold: 0.95
    block_effort: 6.5
    block_speed: 1.0
    block_duration: 0.05
    block_overtime: 1.0
    anti_block_angle: 0.3
    anti_block_threshold: 0.1
    qd_10: 390.0
    qd_16: 550.0
    lf_extra_rotat_speed: 110
