controllers:
  upper_gimbal_controller:
    type: rm_gimbal_controllers/Controller
    time_compensation: 0.004
    publish_rate: 100
    chassis_angular_data_num: 20
    detection_topic: "/upper_detection"
    camera_topic: "/upper_camera/camera_info"
    detection_frame: "upper_detection"
    yaw:
      joint: "upper_yaw_joint"
      pid: { p: 5.0, i: 0, d: 0.3, i_clamp_max: 0.0, i_clamp_min: -0.0, antiwindup: true, publish_state: true }
    pitch:
      joint: "upper_pitch_joint"
      pid: { p: 8.0, i: 50, d: 0.3, i_clamp_max: 0.1, i_clamp_min: -0.1, antiwindup: true, publish_state: true }
    bullet_solver:
      resistance_coff_qd_10: 0.45
      resistance_coff_qd_15: 0.4
      resistance_coff_qd_16: 0.7
      resistance_coff_qd_18: 0.55
      resistance_coff_qd_30: 3.0
      g: 9.81
      delay: 0.2
      dt: 0.001
      timeout: 0.001
      publish_rate: 50
    moving_average_filter:
      is_debug: true
      center_offset_z: 0.05
      pos_data_num: 20
      vel_data_num: 30
      center_data_num: 100
      gyro_data_num: 100
  lower_gimbal_controller:
    type: rm_gimbal_controllers/Controller
    time_compensation: 0.004
    publish_rate: 100
    chassis_angular_data_num: 20
    detection_topic: "/lower_detection"
    camera_topic: "/lower_camera/camera_info"
    detection_frame: "lower_detection"
    yaw:
      joint: "lower_yaw_joint"
      pid: { p: 5.0, i: 0, d: 0.3, i_clamp_max: 0.0, i_clamp_min: -0.0, antiwindup: true, publish_state: true }
    pitch:
      joint: "lower_pitch_joint"
      pid: { p: 5.0, i: 100, d: 0.2, i_clamp_max: 0.4, i_clamp_min: -0.4, antiwindup: true, publish_state: true }
    bullet_solver:
      resistance_coff_qd_10: 0.45
      resistance_coff_qd_15: 0.4
      resistance_coff_qd_16: 0.7
      resistance_coff_qd_18: 0.55
      resistance_coff_qd_30: 3.0
      g: 9.81
      delay: 0.2
      dt: 0.001
      timeout: 0.001
      publish_rate: 50
    moving_average_filter:
      is_debug: true
      center_offset_z: 0.05
      pos_data_num: 20
      vel_data_num: 30
      center_data_num: 100
      gyro_data_num: 100
