name: bloom-release
on:
  push:
    paths:
      - package.xml
      - '*/package.xml'
    branches:
      - master
  workflow_dispatch:

jobs:
  bloom-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: bloom release
        id: bloom
        uses: at-wat/bloom-release-action@v0
        with:
          ros_distro: noetic
          github_token_bloom: ${{ secrets.BLOOM_GITHUB_TOKEN }}
          github_user: qiayuanliao
          git_user: qiayuan
          git_email: liaoqiayuan@gmail.com
          release_repository_push_url: https://github.com/${{ github.repository }}-release.git
          tag_and_release: true
          open_pr: true
          debug_bloom: true
      - name: create GitHub release
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bloom.outputs.version }}
          release_name: Release ${{ steps.bloom.outputs.version }}
