
name: ros-build

on:
  push:
    branches: [ master ]
  label:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'rm-controls/rm_controllers' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: noetic
      - name: Add custom source
        run: |
          mkdir /tmp/custom
          cd /tmp/custom
          wget -i <( curl https://api.github.com/repos/rm-controls/rm_control/releases/latest | \
          grep  "browser_download_url" | \
          sed -e "s/\"//g" | \
          sed -e "s/browser_download_url://g" |\
          sed -e "s/^[ \t]*//g" ) && \
          sudo dpkg -i *.deb || \
          sudo apt-get -f -y install
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros1-distro: noetic
      - name: Package deb
        run: ./.github/scripts/package.sh
      - name: Upload deb package to source
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SOURCE_SSH_HOST }}
          username: ${{ secrets.SOURCE_SSH_NAME }}
          key: ${{ secrets.SOURCE_SSH_KEYGEN }}
          source: "*.deb"
          target: "/usr/local/web/rm-source/ubuntu/incoming/"
      - name: Deploy deb package to source
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SOURCE_SSH_HOST }}
          username: ${{ secrets.SOURCE_SSH_NAME }}
          key: ${{ secrets.SOURCE_SSH_KEYGEN }}
          script: |
                  cd /usr/local/web/rm-source/ubuntu/incoming/
                  reprepro  -s  -b  /usr/local/web/rm-source/ubuntu/  --waitforlock  1000  includedeb focal /usr/local/web/rm-source/ubuntu/incoming/*.deb && \
                  rm -f *.deb
